name: Auto Commit Bot

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"
    push:
        branches:
            - main

jobs:
    auto_commit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Random Multiple Commits with Delay
              run: |
                  git config --local user.email "${{ secrets.USER_EMAIL }}"
                  git config --local user.name "${{ secrets.USER_NAME }}"

                  NUM_COMMITS=$(( ( RANDOM % 5 ) + 3 ))
                  echo "Hari ini bot akan melakukan $NUM_COMMITS commit."

                  for i in $(seq 1 $NUM_COMMITS); do
                    DELAY=$(( ( RANDOM % 46 ) + 15 ))
                    echo "Jeda commit ke-$i: Menunggu $DELAY detik..."
                    sleep $DELAY
                    
                    echo "Automated update part $i on: $(date)" >> bot-log.txt
                    git add bot-log.txt
                    git commit -m "chore: auto update part $i"
                  done

                  git pull --rebase origin main
                  git push origin main
