name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
      - main 

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: athul/waka-readme-stats@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          LANG_COUNT: 8 
          SHOW_TIME: true
          SHOW_TOTAL: true
          IGNORED_LANGUAGES: "JSON, YAML, Text, Markdown" 
          BLOCKS: ▰▱
